apiVersion: apps/v1
kind: Deployment
metadata:
  name: AppName
  namespace: AppNamespace
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: mycontainer
        image: devopsjourney1/mywebapp:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: mykustom-map
        resources:
          requests:
            memory: 16Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 100m

